CREATE DATABASE ENVIAR;
USE ENVIAR;

CREATE TABLE USUARIOS(
CODIGO INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
NOME VARCHAR (50) NOT NULL,
SENHA VARCHAR(50)NOT NULL, 
EMAIL VARCHAR(50) NOT NULL,
ENDERECO VARCHAR(50) NOT NULL,
SEXO CHAR(2) NOT NULL,
TELEFONE CHAR(15) NOT NULL
)ENGINE=INNODB;

CREATE TABLE CATEGORIAS(
CODIGO INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
NOME VARCHAR(50) NOT NULL,
USUARIOS_CODIGO INT UNSIGNED NOT NULL,
FOREIGN KEY(USUARIOS_CODIGO) REFERENCES USUARIOS(CODIGO)
)ENGINE=InnoDB;

CREATE TABLE CONTAS(
CODIGO INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
NOME VARCHAR(50) NOT NULL,
TIPO VARCHAR(50) NOT NULL,
CATEGORIAS_CODIGO INT UNSIGNED NOT NULL,
FOREIGN KEY(CATEGORIAS_CODIGO) REFERENCES CATEGORIAS(CODIGO),
USUARIOS_CODIGO INT UNSIGNED NOT NULL,
FOREIGN KEY(USUARIOS_CODIGO) REFERENCES USUARIOS(CODIGO)
)ENGINE=INNODB;
select co.CODIGO, co.NOME, co.TIPO, ca.NOME as CATEGORIA from contas co JOIN categorias ca ON ca.CODIGO = co.CATEGORIAS_CODIGO where ca.usuarios_codigo = 1;
SELECT * FROM CONTAS;

CREATE TABLE LANCAMENTO(
CODIGO INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
VALOR DOUBLE NOT NULL,
CONTAS_CODIGO INT UNSIGNED NOT NULL,
FOREIGN KEY(CONTAS_CODIGO) REFERENCES CONTAS(CODIGO),
USUARIOS_CODIGO INT UNSIGNED NOT NULL,
FOREIGN KEY(USUARIOS_CODIGO) REFERENCES USUARIOS(CODIGO)
)ENGINE=INNODB;

SELECT * FROM LANCAMENTO;


/**insert into USUARIOSS(CODIGO, NOME, SENHA, EMAIL, ENDERECO, TELEFONE)
values (null, 'pedro', 'senha', 'gmail@a', 'rua do aluno', '00 4334-4565');
**/

select * from USUARIOS;